---
# tasks file for php
- apt: update_cache=yes

# Common configurations to be run on all hosts
# http://www.sitepoint.com/run-multiple-versions-php-one-server/
- name: Install default packages
  apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - gcc
    - make
    - libc-dev
    - bison
    - libtool
    - re2c
    - autoconf
    - automake
  tags:
    - apt

