---
- apt: update_cache=yes

# Common configurations to be run on all hosts
- name: clean exakat
  shell: rm -f exakat.phar

- name: download exakat
  get_url: url=http://dist.exakat.io/versions/index.php?file=exakat-0.4.4.phar dest=/home/vagrant/exakat.phar mode=0777
 
- name: test exakat
  shell: php exakat.phar doctor

## Still needs to modify the config/config.ini file