---
- name: add java repository
  apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main' state=present

- name: add java src repository
  apt_repository: repo='deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu precise main' state=present

- name: add java key repository
  apt_key: id=EEA14886 keyserver=keyserver.ubuntu.com state=present

- name: Accept Java 8 Licence
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | tee /etc/oracle-java-8-licence-acceptance | /usr/bin/debconf-set-selections
  args:
    creates: /etc/oracle-java-8-licence-acceptance

- apt: update_cache=yes

- name: downlad neo4j
  get_url: url=http://dist.neo4j.org/neo4j-community-2.2.4-unix.tar.gz dest=/home/vagrant/neo4j.tar.gz mode=0750

# Common configurations to be run on all hosts
- name: Install default packages
  apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items:
  - silversearcher-ag
  - tree
  - vim
  - git
  - php5-cli
  - zip
  - wkhtmltopdf
  - maven
  - php5-mysqlnd
  - sqlite
  - gcc
  - make
  - libxml2-dev
  - autoconf
  - re2c
  - bison
  - screen
  - php5-curl
  - php5-sqlite
  - libssl-dev
  - libcurl4-openssl-dev
  - pkg-config
  - libbz2-dev
  - libjpeg-dev
  - libpng-dev
  - libfreetype6-dev
  - libgmp3-dev
  - libldap2-dev
  - libmcrypt-dev
  - libmhash-dev
  - freetds-dev
  - libz-dev
  - ncurses-dev
  - libpcre3-dev
  - libsqlite-dev
  - libaspell-dev
  - libreadline6-dev
  - librecode-dev
  - python-software-properties
  - libxpm-dev
  - unixodbc-dev
  - oracle-java8-installer
  - ca-certificates
  - oracle-java8-set-default
    #- libt1-dev
  tags:
    - apt

- name: untar neo4j
  shell: tar -xvf /home/vagrant/neo4j.tar.gz

- name: move neo4j
  shell: mv neo4j-community-2.2.4 neo4j

- name: clone gremlin neo4j
  git: repo=https://github.com/thinkaurelius/neo4j-gremlin-plugin.git dest=/home/vagrant/neo4j-gremlin-plugin
